# Generated by Django 5.2 on 2025-05-08 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_compte_groups_compte_is_staff_compte_is_superuser_and_more'),
        ('formation', '0003_cours'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionExam',
            fields=[
                ('id_question_exam', models.AutoField(primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id_exam', models.AutoField(primary_key=True, serialize=False)),
                ('evaluation_state', models.BooleanField(default=False, help_text='True = Evaluation open, False = Evaluation closed', verbose_name='Evaluation State')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='formation.niveaux')),
            ],
        ),
        migrations.CreateModel(
            name='AutoCorrectionExam',
            fields=[
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='auto_correction', serialize=False, to='examen.questionexam')),
                ('note', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ChoixExam',
            fields=[
                ('id_choix_exam', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('est_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(limit_choices_to={'auto_correction__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='examen.questionexam')),
            ],
            options={
                'verbose_name_plural': 'Choix Exams',
            },
        ),
        migrations.AddField(
            model_name='questionexam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='examen.exam'),
        ),
        migrations.CreateModel(
            name='ReponseExamManuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.TextField()),
                ('date_passer_exam', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_manuel', to='account.etudiant')),
                ('question', models.ForeignKey(limit_choices_to={'auto_correction__isnull': True}, on_delete=django.db.models.deletion.CASCADE, to='examen.questionexam')),
            ],
            options={
                'verbose_name_plural': 'Reponses Exam Manuel',
                'unique_together': {('etudiant', 'question')},
            },
        ),
        migrations.CreateModel(
            name='ReponseExamAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_passer_exam', models.DateTimeField(auto_now_add=True)),
                ('choix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.choixexam')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_auto', to='account.etudiant')),
                ('question', models.ForeignKey(limit_choices_to={'auto_correction__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='examen.questionexam')),
            ],
            options={
                'verbose_name_plural': 'Reponses Exam Auto',
                'unique_together': {('etudiant', 'question')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationResultExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField()),
                ('date_evaluation', models.DateTimeField(auto_now_add=True)),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.formateur')),
                ('reponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='examen.reponseexammanuel')),
            ],
            options={
                'verbose_name_plural': 'Evaluation Results Exam',
                'unique_together': {('reponse', 'formateur')},
            },
        ),
    ]
