# Generated by Django 5.2 on 2025-04-24 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('ID_Utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('Date_naissance', models.DateField()),
                ('Telephone', models.CharField(max_length=15)),
                ('Sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('type', models.CharField(choices=[('etudiant', 'Etudiant'), ('gerant', 'Gérant'), ('formateur', 'Formateur')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('ID_Utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='etudiant', serialize=False, to='account.utilisateur')),
                ('speciality', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('ID_Utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='formateur', serialize=False, to='account.utilisateur')),
                ('Domaine_expertise', models.CharField(max_length=100)),
                ('Experience_annees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gerant',
            fields=[
                ('ID_Utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='gerant', serialize=False, to='account.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('etat', models.BooleanField(default=True)),
                ('utilisateur', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compte_rel', to='account.utilisateur')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
