# Generated by Django 5.2 on 2025-05-13 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_compte_groups_compte_is_staff_compte_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('ID_Diplome', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('formateur', models.ForeignKey(limit_choices_to={'type': 'formateur'}, on_delete=django.db.models.deletion.CASCADE, related_name='diplomes', to='account.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='PointInterest',
            fields=[
                ('ID_point_interest', models.AutoField(primary_key=True, serialize=False)),
                ('point_interest', models.CharField(max_length=255)),
                ('etudiant', models.ForeignKey(limit_choices_to={'type': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='points_interet', to='account.utilisateur')),
            ],
        ),
    ]
