# Generated by Django 5.2 on 2025-05-11 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_compte_groups_compte_is_staff_compte_is_superuser_and_more'),
        ('formation', '0003_cours'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcerneReunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.niveaux')),
            ],
        ),
        migrations.CreateModel(
            name='ParticiperReunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etudiant', models.ForeignKey(limit_choices_to={'type': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, to='account.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id_reunion', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('formateur', models.ForeignKey(limit_choices_to={'type': 'formateur'}, on_delete=django.db.models.deletion.CASCADE, related_name='reunions_organisees', to='account.utilisateur')),
                ('niveaux', models.ManyToManyField(related_name='reunions_concernees', through='reunion.ConcerneReunion', to='formation.niveaux')),
                ('participants', models.ManyToManyField(limit_choices_to={'type': 'etudiant'}, related_name='reunions_participantes', through='reunion.ParticiperReunion', to='account.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='participerreunion',
            name='reunion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reunion.reunion'),
        ),
        migrations.AddField(
            model_name='concernereunion',
            name='reunion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reunion.reunion'),
        ),
        migrations.AlterUniqueTogether(
            name='participerreunion',
            unique_together={('reunion', 'etudiant')},
        ),
        migrations.AlterUniqueTogether(
            name='concernereunion',
            unique_together={('reunion', 'niveau')},
        ),
    ]
