# Generated by Django 5.2 on 2025-05-16 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_diplome_pointinterest'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='compte',
        ),
        migrations.AddField(
            model_name='feedback',
            name='date_reponse',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='etudiant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.etudiant'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='formateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.formateur'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='gerant_reponse',
            field=models.TextField(blank=True, null=True),
        ),
    ]
