# Generated by Django 5.2 on 2025-05-16 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_diplome_pointinterest'),
        ('feedback', '0002_remove_feedback_compte_feedback_date_reponse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='etudiant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='account.etudiant'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='formateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='account.formateur'),
        ),
    ]
