# Generated by Django 5.2 on 2025-05-16 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_diplome_pointinterest'),
        ('feedback', '0003_alter_feedback_etudiant_alter_feedback_formateur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='etudiant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.etudiant'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='formateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.formateur'),
        ),
    ]
