# Generated by Django 5.2 on 2025-05-11 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_compte_groups_compte_is_staff_compte_is_superuser_and_more'),
        ('formation', '0003_cours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id_question', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('reponse', models.TextField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(blank=True, limit_choices_to={'type': 'etudiant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_etudiant', to='account.utilisateur')),
                ('formateur', models.ForeignKey(blank=True, limit_choices_to={'type': 'formateur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_formateur', to='account.utilisateur')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='formation.niveaux')),
            ],
        ),
    ]
