# Generated by Django 5.2 on 2025-04-27 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_compte_groups_compte_is_staff_compte_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoteCles',
            fields=[
                ('id_mote_cles', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CONCEPT', 'Concept'), ('TECHNO', 'Technologie'), ('METHODE', 'Méthodologie')], max_length=20)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id_formation', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('categorie', models.CharField(max_length=100)),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations_crees', to='account.formateur')),
            ],
        ),
        migrations.CreateModel(
            name='presiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.formation')),
                ('mot_cle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.motecles')),
            ],
            options={
                'unique_together': {('formation', 'mot_cle')},
            },
        ),
        migrations.AddField(
            model_name='motecles',
            name='formations',
            field=models.ManyToManyField(through='formation.presiser', to='formation.formation'),
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id_requirements', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequis', to='formation.formation')),
            ],
            options={
                'verbose_name_plural': 'Requirements',
                'ordering': ['ordre'],
            },
        ),
    ]
