# Generated by Django 5.2 on 2025-05-01 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_compte_groups_compte_is_staff_compte_is_superuser_and_more'),
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveaux',
            fields=[
                ('id_niveau', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='formation.formation')),
            ],
            options={
                'verbose_name_plural': 'Niveaux',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Inscrit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('paye', models.BooleanField(default=False)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.etudiant')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.niveaux')),
            ],
            options={
                'ordering': ['-date_inscription'],
                'unique_together': {('niveau', 'etudiant')},
            },
        ),
    ]
