# Generated by Django 5.2 on 2025-05-02 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_niveaux_inscrit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('ID_Cours', models.AutoField(primary_key=True, serialize=False)),
                ('Titre', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Duree', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('Type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('audio', 'Audio')], max_length=20)),
                ('url', models.URLField()),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='formation.niveaux')),
            ],
            options={
                'verbose_name_plural': 'Cours',
                'ordering': ['ordre'],
            },
        ),
    ]
