# Generated by Django 5.2 on 2025-05-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0003_cours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motecles',
            name='formations',
            field=models.ManyToManyField(related_name='mote_cles', through='formation.presiser', to='formation.formation'),
        ),
    ]
