# Generated by Django 5.2 on 2025-05-02 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formation', '0003_cours'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTest',
            fields=[
                ('ID_QuestionTest', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('auto', 'Auto-corrected'), ('manuel', 'Manual correction')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AutoCorrectionTest',
            fields=[
                ('question', models.OneToOneField(limit_choices_to={'type': 'auto'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='auto_correction', serialize=False, to='test.questiontest')),
                ('note_question', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ManuelCorrectionTest',
            fields=[
                ('question', models.OneToOneField(limit_choices_to={'type': 'manuel'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='manual_correction', serialize=False, to='test.questiontest')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('ID_Test', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField()),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='formation.formation')),
            ],
        ),
        migrations.AddField(
            model_name='questiontest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='test.test'),
        ),
        migrations.CreateModel(
            name='ChoixTest',
            fields=[
                ('ID_ChoixTest', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('Est_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='test.autocorrectiontest')),
            ],
        ),
    ]
