# Generated by Django 5.2 on 2025-05-03 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_compte_groups_compte_is_staff_compte_is_superuser_and_more'),
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReponseTestManuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.TextField()),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.etudiant')),
                ('question', models.ForeignKey(limit_choices_to={'type': 'manuel'}, on_delete=django.db.models.deletion.CASCADE, to='test.questiontest')),
            ],
            options={
                'unique_together': {('etudiant', 'question')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationResultTest',
            fields=[
                ('reponse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='test.reponsetestmanuel')),
                ('note', models.PositiveIntegerField()),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.formateur')),
            ],
        ),
        migrations.CreateModel(
            name='ReponseTestAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.etudiant')),
                ('question', models.ForeignKey(limit_choices_to={'type': 'auto'}, on_delete=django.db.models.deletion.CASCADE, to='test.questiontest')),
                ('reponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.choixtest')),
            ],
            options={
                'unique_together': {('etudiant', 'question')},
            },
        ),
    ]
