# Generated by Django 5.2 on 2025-05-22 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_reponsetestmanuel_evaluationresulttest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choixtest',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='test.autocorrectiontest'),
        ),
    ]
